### ISSUE TITLE
Contract storage page is still referring to the old cairo syntax

### ISSUE THREAD

**Issue by glihm** [starknet-io/starknet-docs#883]
**Describe the bug**
Smart contract storage page is still using outdated cairo syntax and decorators.
(Not sure if it can be considered as a bug or a feature, I do apologize if bug is not appropriate).

**To Reproduce**
1. Go to [storage page](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/contract-storage/).

**Expected behavior**
Updated content for the new syntax.

**Desktop (please complete the following information):**
Any version.

**Additional context**
I would love to try submitting a PR to edit this content if you agree.

**Comment by glihm** [comment]
Quick question also, with components, is the address still computed the same way? And we do need to take care about not having several components with the same variables names in the storage?
I'm diving in the compiler code to check about this, any insights would be very helpful. Thank you!

**Comment by ArielElp** [comment]
I think that the page was updated since the time of the issue. In any case, with v0 components, you cannot have the same storage var name in two different components, and compilation will fail. The vision there is to have the storage/events of each component lie in their own space (e.g. via an offset determined at the contract), or, more generally, give the contract some convenient way of determining the layout of the different components in storage.
