### ISSUE TITLE
feat: add codespell linter workflow for CI

### ISSUE THREAD

**Issue by xiaolou86** [starknet-io/starknet-docs#954]
Codespell linter tool is very important for code and system quality, especially for enhancing docs readability.

So I want to add codespell linter workflow for CI.

**Comment by stoobie** [comment]
@xiaolou86 I merged #1007 . Thanks for adding it! However, now when it comes across a typo in a PR, instead of just fixing it, it throws an error that stops the rest of the workflows.

It finds a typo, which throws an error that kills subsequent workflows. I manually fix the typo and then commit the change. Then, if it finds another typo, again, it throws an error that kills subsequent workflows, and the process repeats until there aren't any more typos.

Can you think of a way to make this more efficient? And I'm not sure why it didn't just fix the typos itself.

**Comment by xiaolou86** [comment]
@stoobie All the workflows run independenly. But we added the logic that let `typo` firstly before other workflows, as a result, if `typo` goes to fail, others will stop.

**Comment by xiaolou86** [comment]
So if we want to let all the jobs run independently, delete the dependency relationship.

```
  test-deploy:
    name: Test deploy
    runs-on: ubuntu-latest
    #needs:
    #  - typos
```


I will try to create a new PR.

**Comment by xiaolou86** [comment]
> @xiaolou86 I merged #1007 . Thanks for adding it! However, now when it comes across a typo in a PR, instead of just fixing it, it throws an error that stops the rest of the workflows.
> 
> It finds a typo, which throws an error that kills subsequent workflows. I manually fix the typo and then commit the change. Then, if it finds another typo, again, it throws an error that kills subsequent workflows, and the process repeats until there aren't any more typos.
> 
> Can you think of a way to make this more efficient? And I'm not sure why it didn't just fix the typos itself.

#1055 
@stoobie help me to review.

**Comment by xiaolou86** [comment]
btw, it will try to find all the typos not only one at a time.

**Comment by stoobie** [comment]
@xiaolou86 Great, thanks. I'll take a look next week.
